IBC/IBC/Models/POCO/Extrato.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IBC.Models
{
    public class Extrato
    {
        public List<Movimentacao> lsMovimentacao { get; set; }
    }
}

IBC/IBC/Models/ViewModel/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using IBC.Controllers;

namespace IBC.Models
{
    public class paginaInicialView
    {
        
        public string saldo { get; set; }
        public string lsCoMenusDisponiveis { get; set; }
        public int co_cliente { get; set; }

        public paginaInicialView(ConectaIBC ibc)
        {            
            this.saldo = ibc.saldo.saldo;
            this.lsCoMenusDisponiveis = string.Join(",", new MenuFavoritoController().getLsCoMenuFavoritos(ibc.co_cliente).ToArray());
            this.co_cliente = ibc.co_cliente;
        }
    }

    public class sideBarView
    {
        public string nomeCliente { get; set; }
        public string agencia { get; set; }
        public string contaCorrente { get; set; }
        public bool ic_trocarConta { get; set; }
        public Categoria categoria { get; set; }

        public sideBarView(ConectaIBC ibc)
        {
            //Verifica se o cliente possui mais de uma conta, acionando o botão de Trocar Conta
            this.ic_trocarConta = ibc.contaCliente.contas.Count() > 1 ? true : false;

            Conta conta = ibc.contaCliente.contas.FirstOrDefault();

            this.nomeCliente = ibc.dadosUsuario.nome.Trim();
            this.agencia = conta.agencia;
            this.contaCorrente = conta.conta.TrimStart(new Char[] { '0' });
            this.categoria = ibc.categoria;
        }
    }

    public class navBarView
    {
        public string nomeCliente { get; set; }
        public string dtAcesso { get; set; }

        public navBarView(ConectaIBC ibc)
        {
            this.nomeCliente = ibc.dadosUsuario.nome.Split(new Char[] { ' ' }).First().Trim();
            this.dtAcesso = "Último acesso em " + ibc.dadosUsuario.dataUltimoAcesso + " às " + ibc.dadosUsuario.horaUltimoAcesso;
        }
    }

    public class CapturaSaldo
    {
        public Saldo saldo { get; set; }

        public CapturaSaldo(ConectaIBC ibc)
        {
            this.saldo = ibc.CapturaSaldoCompleto(ibc);
        }
    }

    public class CapturaExtrato
    {
        public Extrato extrato { get; set; }

        public CapturaExtrato(ConectaIBC ibc)
        {
            this.extrato = ibc.CapturaExtrato5Dias();
        }

        public CapturaExtrato(ConectaIBC ibc, DateTime hdnDataInicio, DateTime hdnDataFinal, string rdoTipoExtrato, int sltOutroMes, int txtDataInicio, int txtDataFinal)
        {
            this.extrato = ibc.getExtratoPorPeriodo(hdnDataInicio, hdnDataFinal, sltOutroMes, txtDataInicio, txtDataFinal);
        }
    }

    public class buscaPontosCAIXA
    {
        public int saldo { get; set; }
        public int expirar { get; set; }

        public buscaPontosCAIXA(int co_cliente)
        {
            this.saldo = new PontosCaixaController().getPontosCAIXA(co_cliente);
            this.expirar = new PontosCaixaController().getPontosCAIXAaExpirar(co_cliente);
        }
    }

    public class loteriaView
    {
        public List<int> lsQtdNrs { get; set; }

        public loteriaView()
        {
            this.lsQtdNrs = new List<int> { 6,7,8,9 };
        }
    }
}

IBC/IBC/Controllers/HomeController.cs
using IBC.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace IBC.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string nomeUsuario, string password)
        {
            ConectaIBC ibc = new ConectaIBC(nomeUsuario, password);
            ibc.RecebeSeed();
            ibc.EnviaChave();
            ibc.EnviaUsuario();
            ibc.EnviaSenha();
            ibc.CapturaSaldo();
            ibc.CapturaCliente();
            ibc.CapturaCategoria();
            ibc.CapturaAlertas();
            ibc.CapturaDadosUsuario();

            Conta conta = ibc.contaCliente.contas.FirstOrDefault();

            ibc.co_cliente = new ClienteController().getCliente(nomeUsuario, conta.cpf);
            if (ibc.co_cliente == 0)
            {
                ibc.co_cliente = new ClienteController().addCliente(conta.agencia, conta.conta, ibc.dadosUsuario.nome, conta.cpf, nomeUsuario);
            }

            Session["__IBC__"] = ibc;

            return RedirectToAction("Home");
        }

        public ActionResult Home()
        {
            ConectaIBC ibc = Session["__IBC__"] as ConectaIBC;

            ViewBag.saldoConta = ibc.saldo.saldo;

            return View(new paginaInicialView(ibc));
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult SideBar()
        {
            ConectaIBC ibc = Session["__IBC__"] as ConectaIBC;

            return PartialView("_SideBar", new sideBarView(ibc));
        }

        public ActionResult NavBar()
        {
            ConectaIBC ibc = Session["__IBC__"] as ConectaIBC;

            return PartialView("_Navbar", new navBarView(ibc));
        }

        public ActionResult Saldo()
        {
            ConectaIBC ibc = Session["__IBC__"] as ConectaIBC;

            return PartialView("_SaldoBox", new CapturaSaldo(ibc));
        }

        public ActionResult PontosCAIXA()
        {
            ConectaIBC ibc = Session["__IBC__"] as ConectaIBC;

            return PartialView("_PontosCAIXABox", new buscaPontosCAIXA(ibc.co_cliente));
        }

        public ActionResult Extrato()
        {
            ConectaIBC ibc = Session["__IBC__"] as ConectaIBC;

            return PartialView("_Extrato", new CapturaExtrato(ibc));
        }

        public ActionResult getExtratoPorPeriodo(DateTime hdnDataInicio, DateTime hdnDataFinal, string rdoTipoExtrato, int sltOutroMes, int txtDataInicio, int txtDataFinal)
        {
            ConectaIBC ibc = Session["__IBC__"] as ConectaIBC;

            return PartialView("_ExtratoTable", new CapturaExtrato(ibc, hdnDataInicio, hdnDataFinal, rdoTipoExtrato, sltOutroMes, txtDataInicio, txtDataFinal));
        }
    }
}

IBC/IBC/Controllers/LoteriaController.cs
using IBC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IBC.Controllers
{
    public class LoteriaController : BaseController
    {
        public ActionResult getLoteria()
        {
            ConectaIBC ibc = Session["__IBC__"] as ConectaIBC;

            return PartialView("_Aposta", new loteriaView());
        }
    }
}

IBC/IBC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

IBC/IBC/Views/Home/Home.cshtml
@model IBC.Models.paginaInicialView



@Html.HiddenFor(modelItem => modelItem.co_cliente)
@Html.HiddenFor(modelItem => modelItem.lsCoMenusDisponiveis)

<div class="row">
    <div class="col-lg-8" id="div_menu_favorito_2808">
        @{Html.RenderAction("Saldo");}
    </div>
    <div class="col-lg-4" id="div_menu_favorito_3033">
        @{Html.RenderAction("PontosCaixa");}
    </div>
</div>

<div class="row">
    <div class="col-lg-12" id="div_menu_favorito_2810">
        @{Html.RenderAction("Extrato");}
    </div>
</div>

<div class="row">
    <div class="col-lg-10" id="div_menu_favorito_269">
        @{Html.RenderAction("getLoteria", "Loteria");}
    </div>
</div>

IBC/IBC/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Limitless - Responsive Web Application Kit by Eugene Kopyov</title>

    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
    <link href="~/assets/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
    <link href="~/assets/css/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="~/assets/css/core.css" rel="stylesheet" type="text/css">
    <link href="~/assets/css/components.css" rel="stylesheet" type="text/css">
    <link href="~/assets/css/colors.css" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->
    <!-- Core JS files -->
    <script type="text/javascript" src="~/assets/js/plugins/loaders/pace.min.js"></script>
    <script type="text/javascript" src="~/assets/js/core/libraries/jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/js/core/libraries/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/assets/js/plugins/loaders/blockui.min.js"></script>
    <!-- /core JS files -->
    <!-- Theme JS files -->
    <script type="text/javascript" src="~/assets/js/plugins/forms/validation/validate.min.js"></script>
    <script type="text/javascript" src="~/assets/js/plugins/forms/styling/uniform.min.js"></script>
    <script type="text/javascript" src="~/assets/js/core/app.js"></script>
    <script type="text/javascript" src="~/assets/js/pages/login_validation.js"></script>
    <!-- /theme JS files -->

</head>
<body class="login-container login-cover">
    <!-- Page container -->
    <div class="page-container pb-20">
        <!-- Page content -->
        <div class="page-content">
            <!-- Main content -->
            <div class="content-wrapper">
                <!-- Form with validation -->

                @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { @class = "form-validate" }))
                {
                    <div class="panel panel-body login-form">
                        <div class="text-center">
                            <div class="icon-object border-slate-300 text-slate-300"><i class="icon-reading"></i></div>
                            <h5 class="content-group">Acessar sua conta <small class="display-block">Digite seu login e senha</small></h5>
                        </div>
                        <div class="form-group has-feedback has-feedback-left">
                            <input type="text" class="form-control" placeholder="Usuário" name="nomeUsuario" required="required" value="lucas881302">
                            <div class="form-control-feedback">
                                <i class="icon-user text-muted"></i>
                            </div>
                        </div>
                        <div class="form-group has-feedback has-feedback-left">
                            <input type="password" class="form-control" placeholder="Senha" name="password" required="required" value="fladf17">
                            <div class="form-control-feedback">
                                <i class="icon-lock2 text-muted"></i>
                            </div>
                        </div>
                        <div class="form-group login-options">
                            <div class="row">
                                <div class="col-sm-6">
                                    <label class="checkbox-inline">
                                        <input type="checkbox" class="styled" checked="checked">
                                        Lembrar de mim
                                    </label>
                                </div>
                                <div class="col-sm-6 text-right">
                                    <a href="login_password_recover.html">Esqueci minha senha</a>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn bg-blue btn-block">Acessar <i class="icon-arrow-right14 position-right"></i></button>
                        </div>
                        <div class="content-divider text-muted form-group"><span>ou entrar utilizando sua rede social</span></div>
                        <ul class="list-inline form-group list-inline-condensed text-center">
                            <li><a href="#" class="btn border-indigo text-indigo btn-flat btn-icon btn-rounded"><i class="icon-facebook"></i></a></li>
                            <li><a href="#" class="btn border-pink-300 text-pink-300 btn-flat btn-icon btn-rounded"><i class="icon-dribbble3"></i></a></li>
                            <li><a href="#" class="btn border-slate-600 text-slate-600 btn-flat btn-icon btn-rounded"><i class="icon-github"></i></a></li>
                            <li><a href="#" class="btn border-info text-info btn-flat btn-icon btn-rounded"><i class="icon-twitter"></i></a></li>
                        </ul>
                        <div class="content-divider text-muted form-group"><span>Ainda não possui uma conta?</span></div>
                        <a href="login_registration.html" class="btn btn-default btn-block content-group">Cadastrar</a>
                        <span class="help-block text-center no-margin">Se continuar, você confirma que leu nossos <a href="#">Termos e Condiçoes</a> e <a href="#">as regras de cookies</a></span>
                    </div>
                }
                <!-- /form with validation -->
            </div>
            <!-- /main content -->
        </div>
        <!-- /page content -->
    </div>
    <!-- /page container -->
</body>
</html>

IBC/IBC/Views/Home/_Extrato.cshtml
@model IBC.Models.CapturaExtrato

<link href="~/assets/css/icons/fontawesome/styles.min.css" rel="stylesheet" />

<!-- Theme JS files -->
<script type="text/javascript" src="~/assets/js/plugins/pickers/daterangepicker.js"></script>
<script type="text/javascript" src="~/assets/js/plugins/pickers/anytime.min.js"></script>
<script type="text/javascript" src="~/assets/js/plugins/pickers/pickadate/picker.js"></script>
<script type="text/javascript" src="~/assets/js/plugins/pickers/pickadate/picker.date.js"></script>
<script type="text/javascript" src="~/assets/js/plugins/pickers/pickadate/picker.time.js"></script>
<script type="text/javascript" src="~/assets/js/pages/picker_date.js"></script>



<!-- /theme JS files -->
<!-- Basic panel controls -->
<div class="panel panel-white border-top-lg border-top-blue">
    <div class="panel-heading">
        <h6 class="panel-title">Extrato</h6>
        <div class="heading-elements">
            <button type="button" class="btn btn-link daterange-ranges pickadate-translated-pt-br heading-btn text-semibold">
                <i class="icon-calendar3 position-left"></i> <span></span> <b class="caret"></b>
            </button>

            <ul class="icons-list">
                <li><a data-action="collapse" data-popup="tooltip" title="Esconder"></a></li>
                <li><a class="menu_favorito" id="2810" data-popup="tooltip" title="Favorito" onclick="marcarFavorito(this)"><i class="icon-star-empty3"></i></a></li>
                <li><a data-action="closeElement" onclick="fecharElement(2810)" data-popup="tooltip" title="Fechar"></a></li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        <div class="row" id="extratoTable">
            @{Html.RenderPartial("_ExtratoTable", Model);}


        </div>
        <div class="row">
            <div id="extrato-stats"></div>
            <div class="chart-container">
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <div class="heading-elements">
            <span class="heading-text text-semibold"></span>
            <ul class="icons-list pull-right">
                <li><a href="#" data-popup="tooltip" title="Imprimir"><i class="icon-printer2"></i></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-popup="tooltip" title="Gerar em arquivo"><i class="icon-file-download"></i> <span class="caret"></span></a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li><a href="#">TXT</a></li>
                        <li><a href="#">OFC</a></li>
                        <li><a href="#">OFX</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- /basic panel controls -->
<script type="text/javascript" src="~/assets/js/plugins/visualization/d3/d3.min.js"></script>
<script type="text/javascript" src="~/assets/js/plugins/visualization/d3/d3_tooltip.js"></script>
<script src="~/Scripts/_Extrato.js"></script>

IBC/IBC/Views/Home/_ExtratoTable.cshtml
@model IBC.Models.CapturaExtrato

<div class="table-responsive">
    <table class="table table_extrato">
        <thead>
            <tr>
                <th>Data Movimentação</th>
                <th>Nr. Documento</th>
                <th>Histórico</th>
                <th>Valor</th>
                <th>Saldo</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var movimentacao in Model.extrato.lsMovimentacao)
            {
                <tr>
                    <td class="extrato_data">@movimentacao.dt_movimentacao</td>
                    <td>@movimentacao.nr_doc</td>
                    <td>@movimentacao.historico</td>
                    <td>@movimentacao.valor</td>
                    <td class="extrato_saldo">@movimentacao.saldo</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<hr />

IBC/IBC/Views/Home/_SaldoBox.cshtml
@model IBC.Models.CapturaSaldo


						
<!-- Basic panel controls -->
<div class="panel panel-white border-top-lg border-top-blue">
    <div class="panel-heading">
        <h6 class="panel-title">Saldo</h6>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse" data-popup="tooltip" title="Esconder"></a></li>
                <li><a class="menu_favorito" id="2808" data-popup="tooltip" title="Favorito" onclick="marcarFavorito(this)"><i class="icon-star-empty3"></i></a></li>
                <li><a data-action="closeElement" onclick="fecharElement(2808)" data-popup="tooltip" title="Fechar"></a></li>
            </ul>
        </div>
    </div>

    <div class="panel-body">
        

        <div class="row">
            <div class="col-md-6">
                <div class="chart-container text-center content-group">
                    <div class="display-inline-block" id="google-pie-3d"></div>
                </div>
            </div>
            <div class="col-md-6">
                <!-- Table footer styling -->
                    <div class="table-responsive">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <td>Saldo</td>
                                    <td><span class="vrSaldoPie">@Model.saldo.saldo</span> @Model.saldo.sinalSaldo</td>
                                </tr>
                                <tr>
                                    <td>Limite do Cheque Especial</td>
                                    <td><span class="vrSaldoPie">@Model.saldo.limite</span></td>
                                </tr>
                                <tr>
                                    <td>Saldo bloqueado</td>
                                    <td><span class="vrSaldoPie">@Model.saldo.saldoBloqueado</span></td>
                                </tr>
                                <tr>
                                    <td>Saldo disponivel c/limite</td>
                                    <td>@Model.saldo.saldoDisponivelComLimite</td>
                                </tr>
                            </tbody>
                            <tfoot>
                                <tr class="bg-teal-400">
                                    <th>Saldo total</th>
                                    <th>@Model.saldo.saldoTotal</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                <!-- /table footer styling -->
            </div>
        </div>
    </div>
</div>
<!-- /basic panel controls -->


<!-- Theme JS files -->
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript" src="~/assets/js/charts/google/pies/pie_3d.js"></script>
<!-- /theme JS files -->